#!/bin/bash

if [[ -z "$1" ]] || [[ -z "$2" ]]; then
	echo "Ввод переменных выполнен не полностью!"
	exit
fi
if (("$1" < 1)) || (("$1" > 2)); then
	echo "Ввод варианта фрактала выполнен неверно!"
	exit
fi
if (("$2" < 1)) || (("$2" > 7)); then
	echo "Ввод уровня фрактала выполнен неверно!"
	exit
fi
if ! [[ -e "Main_modules/release" ]]; then
	cd Main_modules
	make
	cd ..
fi
./Main_modules/release $1 $2
