name: Fractal unit-test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    setup_and_build:
      name: Настройка и запуск билда
      runs-on: ubuntu-latest

      steps:
        - name: Установка make
          run: |
            sudo apt update
            sudo apt install make
            
        - name: Взять исходники из Гита
          uses: actions/checkout@v4
            
        - name: Сборка программа
          run: |
            cd 03.Fractal/Codes/Main_modules
            make -f makefile debug
            make -f makefile debug_test
            
        - name: Сохранение результата билда для тестирования
          uses: actions/upload-artifact@v4
          with:
            name: fractal
            path: ${{ github.workspace }}/03.Fractal/Codes/Main_modules
    
    test:
      needs:
        - setup_and_build
        
      name: Тестирование
      runs-on: ubuntu-latest
      steps:
        - name: Загрузка результата билда для тестирования
          uses: actions/download-artifact@v4
          with:
            name: fractal
            path: Codes/Main_modules
        
        - name: Запуск тестирования
          run: |
            cd Codes/Main_modules
            chmod 777 debug_test
            ./debug_test