name: IO Flush 2

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    setup_and_build:
        name: Найстройка и запуск билда
        runs-on: ubuntu-latest

        steps:
          - name: Установка gcc
            run: |
                sudo apt-get update
                sudo apt install build-essential
            
          - name: Взять исходники из Гита
            uses: actions/checkout@v4
            
          - name: Программа собирается
            run: |
                cd 01.IO_flush/Code_auto
                ./io_flush_code
            
          - name: Сохранение результата билда для тестирования
            uses: actions/upload-artifacr@4
            with:
                name: io_flush_auto
                path: ${{ github.workspace }}/01.IO_flush/Code_auto
    
    test:
        needs:
          - setup_and_build
        
        name: Тестирование

        runs-on: ubuntu-latest

        steps:
          - name: Загрузка результата билда для тестирования
            uses: actions/download-artifact@v4
            with:
                name: io_flush_auto
                path: Code_auto
        
          - name: Запуск тестирования
            run: |
            cd 01.IO_flush
            chmod -777 io_flush_auto
            ./io_flush_auto 1
            ./io_flush_auto 2
            ./io_flush_auto 3
            ./io_flush_auto 4