name: Memory Overcommit Windows test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    setup_and_build:
      name: Настройка и запуск билда
      runs-on: windows-latest

      steps:
        - name: Установка gcc
          uses: rlalik/setup-cpp-compiler@master
          with:
            compiler: gcc-latest

        - name: Подтверждение установки
          run: |
            gcc --version
            
        - name: Взять исходники из Гита
          uses: actions/checkout@v4
            
        - name: Программа собирается
          run: |
            cd 02.Memory_Overcommit/Windows_codes
            gcc memory_overcommit_win.c -o memory_overcommit_win
            
        - name: Сохранение результата билда
          uses: actions/upload-artifact@v4
          with:
            name: Windows_codes
            path: ${{ github.workspace }}/02.Memory_Overcommit/Windows_codes/