name: Memory Overcommit Windows test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    setup_and_build:
      name: Настройка и запуск билда
      runs-on: windows-latest

      steps:
        - name: Установка gcc
          run: |
            $Download64 = "https://github.com/niXman/mingw-builds-binaries/releases/download/13.2.0-rt_v11-rev0/x86_64-13.2.0-release-posix-seh-ucrt-rt_v11-rev0.7z"
            $Download32 = "https://github.com/niXman/mingw-builds-binaries/releases/download/13.2.0-rt_v11-rev0/i686-13.2.0-release-posix-dwarf-ucrt-rt_v11-rev0.7z"
            function Add-PathEntry {
              param (
                  $To
              )
              $env:Path += ";$To"
              [Environment]::SetEnvironmentVariable(
                "Path",
                [Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::User) + ";$To",
                [EnvironmentVariableTarget]::User)
            }
            function Invoke-Main {
              $ProgressPreference = 'SilentlyContinue'

              Write-Output "Initializing 7-Zip Module..."
              [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
              Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -Scope CurrentUser
              Set-PSRepository -Name 'PSGallery' -SourceLocation "https://www.powershellgallery.com/api/v2" -InstallationPolicy Trusted
              Install-Module -Name 7Zip4PowerShell -Force -Scope CurrentUser

              Write-Output "Downloading mingw64..."
              Invoke-WebRequest "$Download64" -OutFile ".\amd64.7z"
              Write-Output "Extracting mingw64..."
              Expand-7Zip -ArchiveFileName "amd64.7z" -TargetPath ".\"
              Remove-Item -Path ".\amd64.7z" -Force

              Write-Output "Downloading mingw32..."
              Invoke-WebRequest "$Download32" -OutFile ".\i686.7z"
              Write-Output "Extracting mingw32..."
              Expand-7Zip -ArchiveFileName "i686.7z" -TargetPath ".\"
              Remove-Item -Path ".\i686.7z" -Force

              $ProgressPreference = 'Continue'

              $dest = "$env:APPDATA\mingw-dual"
              Write-Output "Writing to $dest"
              md -Force $dest | Out-Null
              Move-Item -Path ".\*" -Destination "$dest"

              Write-Output "Adding mingw64 to PATH..."
              Add-PathEntry -To "$dest\mingw64\bin"
              Write-Output "Adding mingw32 to PATH..."
              Add-PathEntry -To "$dest\mingw32\bin"
              Write-Output "Done!"
            }
            $origin = (Get-Item .).FullName
            $work = Join-Path $Env:Temp $(New-Guid)
            New-Item -Type Directory -Path $work | Out-Null
            try {
              cd "$work"
              Invoke-Main
            } finally {
              cd "$origin"
              Remove-Item -LiteralPath "$work" -Force -Recurse
            }
            
        - name: Взять исходники из Гита
          uses: actions/checkout@v4
            
        - name: Программа собирается
          run: |
            cd 02.Memory_Overcommit/Windows_codes
            gcc memory_overcommit_win.c -o memory_overcommit_win
            
        - name: Сохранение результата билда
          uses: actions/upload-artifact@v4
          with:
            name: Windows_codes
            path: ${{ github.workspace }}/02.Memory_Overcommit/Windows_codes/